#define HS_RGB_BLINK_INDEX_WIN              53
#define HS_RGB_BLINK_INDEX_MAC              54

/* rgb_record */
#define ENABLE_RGB_MATRIX_RGBR_PLAY
#define RGBREC_CHANNEL_NUM         4
#define EECONFIG_CONFINFO_USE_SIZE 4
#define EECONFIG_RGBREC_USE_SIZE   (RGBREC_CHANNEL_NUM * MATRIX_ROWS * MATRIX_COLS * 2)
#define EECONFIG_USER_DATA_SIZE    (EECONFIG_CONFINFO_USE_SIZE + EECONFIG_RGBREC_USE_SIZE)
#define CONFINFO_EECONFIG_ADDR     (uint32_t *)(EECONFIG_USER_DATABLOCK)
#define RGBREC_EECONFIG_ADDR       (uint8_t *)((uint32_t)EECONFIG_USER_DATABLOCK + (uint32_t)EECONFIG_CONFINFO_USE_SIZE)
